version: "3.9"
services:
  mongo:
    container_name: mongodb
    image: d-mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mongodata:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./mongod_log:/var/log/mongodb/
      - ./init-script.sh:/docker-entrypoint-initdb.d/init-script.sh

    command: mongod --logpath /var/log/mongodb/mongod.log --config /etc/mongod.conf --keyFile /var/lib/mongodb/mongodb-keyfile

    networks:
      my_network:
        ipv4_address: 172.18.0.103

volumes:
  mongodata:

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
